### ISSUE TITLE
Can't build application when using meteor-jade 0.4.6

### ISSUE THREAD

**Issue by deanpapastrat** [mquandalle/meteor-jade#195]
Upgraded to meteor-jade 0.4.6 from 0.4.5, and now when trying to build my Meteor application to publish it to Modulus, it gives the following error:

```
Errors prevented bundling:                    
While processing files with mquandalle:jade (for target web.browser):
packages/blaze-tools/tojs.js:79:1: Unexpected object in HTMLjs in toJS: [object Object]
at [object Object].ToJSVisitor.def.visitObject (packages/blaze-tools/tojs.js:79:1)
at [object Object].HTML.Visitor.def.visit (packages/htmljs/visitors.js:61:1)
at [object Object].ToJSVisitor.def.visitArray (packages/blaze-tools/tojs.js:58:1)
at [object Object].HTML.Visitor.def.visit (packages/htmljs/visitors.js:59:1)
at Object.BlazeTools.toJS (packages/blaze-tools/tojs.js:155:1)
at Object.SpacebarsCompiler.codeGen (packages/spacebars-compiler/compiler.js:89:1)
at _templateGen (plugin/handler.js:66:46)
at packages/underscore/underscore.js:125:1
at _.each._.forEach (packages/underscore/underscore.js:113:1)
at Function._.map._.collect (packages/underscore/underscore.js:124:1)
at JadeCompilerPlugin._fileModeHandler (plugin/handler.js:106:22)
at JadeCompilerPlugin.addCompileResult (plugin/handler.js:33:36)
at caching-compiler.js:305:14
at
/Users/deanpapastrat/.meteor/packages/mquandalle_jade/.0.4.6.esirki++os+web.browser+web.cordova/plugin.compileJadeBatch.os/npm/caching-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/Users/deanpapastrat/.meteor/packages/mquandalle_jade/.0.4.6.esirki++os+web.browser+web.cordova/plugin.compileJadeBatch.os/npm/caching-compiler/node_modules/async/lib/async.js:317:21)
at
/Users/deanpapastrat/.meteor/packages/mquandalle_jade/.0.4.6.esirki++os+web.browser+web.cordova/plugin.compileJadeBatch.os/npm/caching-compiler/node_modules/async/lib/async.js:328:15
at Object.async.forEachLimit.async.eachLimit
(/Users/deanpapastrat/.meteor/packages/mquandalle_jade/.0.4.6.esirki++os+web.browser+web.cordova/plugin.compileJadeBatch.os/npm/caching-compiler/node_modules/async/lib/async.js:221:35)
at JadeCompilerPlugin.processFilesForTarget (caching-compiler.js:277:11)
```

If I revert to meteor-jade 0.4.5, it works perfectly. I didn't upgrade any other packages, just meteor-jade.

**Comment by mquandalle** [comment]
Do you have a clonable reproduction?

**Comment by mquandalle** [comment]
I guess https://github.com/deanpapastrat/bible-bowl-portal/commit/437be79fa7810a56bf9cda7fd0f7f063e04581b8?

**Comment by Almaju** [comment]
Same here! :)

**Comment by ViZhe** [comment]
i too ;(

**Comment by mikeifomin** [comment]
+1

**Comment by mquandalle** [comment]
It seems that the above commit didn’t fix the issue. I have some trouble reproducing the exception.

**Comment by mquandalle** [comment]
Ok, found the problem.

**Comment by deanpapastrat** [comment]
@mquandalle the commit you pulled was exactly what I was referring to. If I can help in any way, let me know!
